linters:
  enable:
    - gofmt
    - gocyclo
    - misspell
    - typecheck
    - errcheck
issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - undeclared name
