dev_addr: 0.0.0.0:8000
docs_dir: content
edit_uri: ""
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/onosproject
  - icon: fontawesome/brands/slack
    link: https://onosproject.slack.com/
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/channel/UCTQaOpqno48GTimdwyfytFw
extra_css:
- styles/css/extra.css
markdown_extensions:
- attr_list
- codehilite
- admonition
- footnotes
nav: null
plugins:
- search:
    lang:
    - en
    separator: '[\s\-\.]+'
- minify:
    minify_html: true
repo_name: onosproject
repo_url: https://github.com/onosproject
site_author: Open Networking Foundation
site_description: Open Network Operating System (ONOS)
site_name: onosproject
site_url: ""
theme:
  custom_dir: theme
  i18n:
    next: Next
    prev: Previous
  icon:
    repo: fontawesome/brands/github-alt
  include_sidebar: true
  language: en
  logo: images/onos_logo_2017.png
  name: material
